import type { Metadata } from 'next'
import { playfair, atkinsonNext, atkinsonMono } from './fonts/fonts'
import '@/styles/globals.scss'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${playfair.variable} ${atkinsonNext.variable} ${atkinsonMono.variable}`}
      >
        {children}
      </body>
    </html>
  )
}
